# Site settings
title: MOOC.fi
baseurl: ""
url: "http://moocfi.github.io"

# Build settings
markdown: redcarpet

sass:
  style: :compressed

navigation:
  "Etusivu": "/"
  "Kurssit": "/kurssit.html"
  "Mikä MOOC?": "/mooc.html"
  "In English": "/english.html"

resources:
  css:
    - "//fonts.googleapis.com/css?family=Alegreya+Sans:400|Noto+Sans:400,700|Open+Sans+Condensed:300,700"
    - "/css/main.css"
  js:
    - "//code.jquery.com/jquery-1.11.0.min.js"
    - "/js/mooc.js"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"